[project]
name = "pipelines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.18"
dependencies = [
    "pandas==2.0.3"
]

[dependency-groups]
dev = [
    "ruff>=0.15.2",
]
